# Generated by Django 3.1.4 on 2020-12-16 00:41

import companymanager.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=300)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.client', verbose_name='Owner of the facility')),
            ],
            options={
                'verbose_name_plural': 'Client facilities',
            },
        ),
        migrations.CreateModel(
            name='ClientIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_industry_name', models.CharField(max_length=400, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Client industry',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order_name', models.CharField(max_length=200)),
                ('order_and_project_number', models.CharField(default='', editable=False, max_length=200)),
                ('order_description', models.TextField(blank=True, default='', null=True)),
                ('order_creation_date', models.DateField(default=datetime.date.today, verbose_name='Date purchase order received')),
                ('expected_order_completion_date', models.DateField(default=companymanager.models.get_target_completion_date, verbose_name='Order target completion date')),
                ('order_completion_date', models.DateField(blank=True, default='', null=True, verbose_name='Order completion date')),
                ('order_budget_total', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_budget_labor', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_budget_material', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_times_reviewed', models.IntegerField(default=0)),
                ('order_model_number', models.CharField(blank=True, default='', max_length=200)),
                ('order_serial_number', models.CharField(blank=True, default='', max_length=200)),
                ('order_customer_PO', models.CharField(blank=True, default='', max_length=200)),
                ('order_invoice_number', models.CharField(blank=True, default='', max_length=200)),
                ('order_internal_notes', models.TextField(blank=True, default='')),
                ('order_client_notes', models.TextField(blank=True, default='')),
                ('order_status', models.CharField(choices=[('OP', 'Opened'), ('QU', 'Quoted'), ('PO', 'PO Received'), ('DA', 'Design Approved'), ('HO', 'Hold'), ('AC', 'Assembly Complete'), ('PI', 'Proceed with Invoices'), ('PS', 'Product Shipped'), ('RS', 'Report Sent'), ('FI', 'Final Invoice Sent'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='OP', max_length=2)),
                ('order_billing', models.CharField(choices=[('FI', 'Fixed'), ('HO', 'Hourly')], default='FI', max_length=2)),
                ('order_facility', models.ManyToManyField(to='companymanager.ClientFacility')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200, unique=True)),
                ('staff_position_in_company', models.CharField(max_length=200)),
                ('staff_start_date_in_company', models.DateField(verbose_name='Date started working at office')),
                ('staff_hourly_salary', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_category_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Staff categories',
            },
        ),
        migrations.CreateModel(
            name='TimeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_code_name', models.CharField(max_length=300, unique=True)),
                ('time_code_description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='StaffTimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_start_time', models.DateTimeField(default=companymanager.models.get_default_task_start_time)),
                ('task_end_time', models.DateTimeField(default=companymanager.models.get_default_task_end_time)),
                ('task_description', models.TextField()),
                ('task_belongs_to_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_present_in_timesheet_of', to='companymanager.order')),
                ('task_time_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_timesheets_of', to='companymanager.timecode', verbose_name='Time code')),
                ('time_sheet_owner', models.ForeignKey(help_text='Employee name', on_delete=django.db.models.deletion.CASCADE, to='companymanager.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.staffcategory'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, unique=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.servicecategory', verbose_name='Category of the Service')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=400)),
                ('project_creation_date', models.DateField(verbose_name='Date project is created')),
                ('project_status', models.CharField(choices=[('OP', 'Opened'), ('IP', 'In Progress'), ('HO', 'Hold'), ('CP', 'Completed'), ('CA', 'Cancelled')], default='OP', max_length=2)),
                ('project_internal_notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.client', verbose_name='Customer of the project')),
                ('project_planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.staff')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planer_of_orders', to='companymanager.staff', verbose_name='Staff member responsible for order execution'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_for_project', to='companymanager.project', verbose_name='Project to which this order is associated'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.service', verbose_name='Type of service provided in this order'),
        ),
        migrations.CreateModel(
            name='ClientDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_department_name', models.CharField(max_length=400)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_user_name', models.CharField(max_length=400)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('account_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.clientindustry'),
        ),
        migrations.AddConstraint(
            model_name='stafftimesheet',
            constraint=models.UniqueConstraint(fields=('time_sheet_owner', 'task_start_time', 'task_end_time'), name='unique_StaffTimeSheet_tasks'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_project', 'order_number'), name='unique_order_id'),
        ),
        migrations.AddConstraint(
            model_name='clientfacility',
            constraint=models.UniqueConstraint(fields=('client_name', 'facility_name'), name='unique_client_facility_id'),
        ),
        migrations.AddConstraint(
            model_name='clientdepartment',
            constraint=models.UniqueConstraint(fields=('client_name', 'client_department_name'), name='unique_client_department_id'),
        ),
        migrations.AddConstraint(
            model_name='clientaccount',
            constraint=models.UniqueConstraint(fields=('client_name', 'account_user_name'), name='unique_client_account_id'),
        ),
    ]
